//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FogGerenciadorDeVendas.ConsultaStatusServiceHomolog {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4", ConfigurationName="ConsultaStatusServiceHomolog.NFeStatusServico4Soap12")]
    public interface NFeStatusServico4Soap12 {
        
        // CODEGEN: Generating message contract since the operation nfeStatusServicoNF is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4/nfeStatusServicoNF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.nfeStatusServicoNFResponse nfeStatusServicoNF(FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.nfeStatusServicoNFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4/nfeStatusServicoNF", ReplyAction="*")]
        System.Threading.Tasks.Task<FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.nfeStatusServicoNFResponse> nfeStatusServicoNFAsync(FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.nfeStatusServicoNFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeStatusServicoNFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeStatusServicoNFRequest() {
        }
        
        public nfeStatusServicoNFRequest(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeStatusServicoNFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4", Order=0)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeStatusServicoNFResponse() {
        }
        
        public nfeStatusServicoNFResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NFeStatusServico4Soap12Channel : FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.NFeStatusServico4Soap12, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NFeStatusServico4Soap12Client : System.ServiceModel.ClientBase<FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.NFeStatusServico4Soap12>, FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.NFeStatusServico4Soap12 {
        
        public NFeStatusServico4Soap12Client() {
        }
        
        public NFeStatusServico4Soap12Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NFeStatusServico4Soap12Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeStatusServico4Soap12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeStatusServico4Soap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.nfeStatusServicoNFResponse FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.NFeStatusServico4Soap12.nfeStatusServicoNF(FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.nfeStatusServicoNFRequest request) {
            return base.Channel.nfeStatusServicoNF(request);
        }
        
        public System.Xml.XmlNode nfeStatusServicoNF(System.Xml.XmlNode nfeDadosMsg) {
            FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.nfeStatusServicoNFRequest inValue = new FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.nfeStatusServicoNFRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.nfeStatusServicoNFResponse retVal = ((FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.NFeStatusServico4Soap12)(this)).nfeStatusServicoNF(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.nfeStatusServicoNFResponse> FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.NFeStatusServico4Soap12.nfeStatusServicoNFAsync(FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.nfeStatusServicoNFRequest request) {
            return base.Channel.nfeStatusServicoNFAsync(request);
        }
        
        public System.Threading.Tasks.Task<FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.nfeStatusServicoNFResponse> nfeStatusServicoNFAsync(System.Xml.XmlNode nfeDadosMsg) {
            FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.nfeStatusServicoNFRequest inValue = new FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.nfeStatusServicoNFRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((FogGerenciadorDeVendas.ConsultaStatusServiceHomolog.NFeStatusServico4Soap12)(this)).nfeStatusServicoNFAsync(inValue);
        }
    }
}
