//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4", ConfigurationName="ConsultaChaveAcessoHomolog.NFeConsultaProtocolo4Soap12")]
    public interface NFeConsultaProtocolo4Soap12 {
        
        // CODEGEN: Generating message contract since the operation nfeConsultaNF is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4/nfeConsultaNF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.nfeConsultaNFResponse nfeConsultaNF(FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.nfeConsultaNFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4/nfeConsultaNF", ReplyAction="*")]
        System.Threading.Tasks.Task<FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.nfeConsultaNFResponse> nfeConsultaNFAsync(FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.nfeConsultaNFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeConsultaNFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeConsultaNFRequest() {
        }
        
        public nfeConsultaNFRequest(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeConsultaNFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4", Order=0)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeConsultaNFResponse() {
        }
        
        public nfeConsultaNFResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NFeConsultaProtocolo4Soap12Channel : FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.NFeConsultaProtocolo4Soap12, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NFeConsultaProtocolo4Soap12Client : System.ServiceModel.ClientBase<FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.NFeConsultaProtocolo4Soap12>, FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.NFeConsultaProtocolo4Soap12 {
        
        public NFeConsultaProtocolo4Soap12Client() {
        }
        
        public NFeConsultaProtocolo4Soap12Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NFeConsultaProtocolo4Soap12Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeConsultaProtocolo4Soap12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeConsultaProtocolo4Soap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.nfeConsultaNFResponse FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.NFeConsultaProtocolo4Soap12.nfeConsultaNF(FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.nfeConsultaNFRequest request) {
            return base.Channel.nfeConsultaNF(request);
        }
        
        public System.Xml.XmlNode nfeConsultaNF(System.Xml.XmlNode nfeDadosMsg) {
            FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.nfeConsultaNFRequest inValue = new FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.nfeConsultaNFRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.nfeConsultaNFResponse retVal = ((FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.NFeConsultaProtocolo4Soap12)(this)).nfeConsultaNF(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.nfeConsultaNFResponse> FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.NFeConsultaProtocolo4Soap12.nfeConsultaNFAsync(FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.nfeConsultaNFRequest request) {
            return base.Channel.nfeConsultaNFAsync(request);
        }
        
        public System.Threading.Tasks.Task<FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.nfeConsultaNFResponse> nfeConsultaNFAsync(System.Xml.XmlNode nfeDadosMsg) {
            FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.nfeConsultaNFRequest inValue = new FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.nfeConsultaNFRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((FogGerenciadorDeVendas.ConsultaChaveAcessoHomolog.NFeConsultaProtocolo4Soap12)(this)).nfeConsultaNFAsync(inValue);
        }
    }
}
