// <auto-generated />
using System;
using FogGerenciadorDeVendas.Dados.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FogGerenciadorDeVendas.Dados.Migrations
{
    [DbContext(typeof(FogContext))]
    partial class FogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FogGerenciadorDeVendas.Dominio.Consumos.Consumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodigoDaComanda")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<DateTime>("DataDeAbertura");

                    b.Property<DateTime?>("DataDeFechamento");

                    b.Property<int>("Quantidade");

                    b.Property<int>("Situacao");

                    b.HasKey("Id");

                    b.ToTable("Consumo");
                });

            modelBuilder.Entity("FogGerenciadorDeVendas.Dominio.Lancamentos.Lancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodigoDaComanda")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<int>("ConsumoId");

                    b.Property<DateTime>("DataDeLancamento");

                    b.Property<int>("ProdutoId");

                    b.HasKey("Id");

                    b.HasIndex("ConsumoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Lancamento");
                });

            modelBuilder.Entity("FogGerenciadorDeVendas.Dominio.Produtos.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataDeCadastro");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<bool>("Situacao");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(16,3)");

                    b.HasKey("Id");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("FogGerenciadorDeVendas.Dominio.Vendas.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ConsumoId");

                    b.Property<DateTime>("DataDaVenda");

                    b.Property<decimal>("PorcentagemDeDesconto");

                    b.Property<decimal>("ValorComDesconto");

                    b.Property<decimal>("ValorTotal");

                    b.HasKey("Id");

                    b.HasIndex("ConsumoId");

                    b.ToTable("Venda");
                });

            modelBuilder.Entity("FogGerenciadorDeVendas.Dominio.Lancamentos.Lancamento", b =>
                {
                    b.HasOne("FogGerenciadorDeVendas.Dominio.Consumos.Consumo", "Consumo")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ConsumoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FogGerenciadorDeVendas.Dominio.Produtos.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FogGerenciadorDeVendas.Dominio.Vendas.Venda", b =>
                {
                    b.HasOne("FogGerenciadorDeVendas.Dominio.Consumos.Consumo", "Consumo")
                        .WithMany()
                        .HasForeignKey("ConsumoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
