//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FogGerenciadorDeVendas.ConsultaReciboHomolog {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRetAutorizacao4", ConfigurationName="ConsultaReciboHomolog.NFeRetAutorizacao4Soap12")]
    public interface NFeRetAutorizacao4Soap12 {
        
        // CODEGEN: Generating message contract since the operation nfeRetAutorizacaoLote is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRetAutorizacao4/NFeRetAutorizacaoLote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FogGerenciadorDeVendas.ConsultaReciboHomolog.nfeRetAutorizacaoLoteResponse nfeRetAutorizacaoLote(FogGerenciadorDeVendas.ConsultaReciboHomolog.nfeRetAutorizacaoLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRetAutorizacao4/NFeRetAutorizacaoLote", ReplyAction="*")]
        System.Threading.Tasks.Task<FogGerenciadorDeVendas.ConsultaReciboHomolog.nfeRetAutorizacaoLoteResponse> nfeRetAutorizacaoLoteAsync(FogGerenciadorDeVendas.ConsultaReciboHomolog.nfeRetAutorizacaoLoteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeRetAutorizacaoLoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRetAutorizacao4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeRetAutorizacaoLoteRequest() {
        }
        
        public nfeRetAutorizacaoLoteRequest(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeRetAutorizacaoLoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRetAutorizacao4", Order=0)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeRetAutorizacaoLoteResponse() {
        }
        
        public nfeRetAutorizacaoLoteResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NFeRetAutorizacao4Soap12Channel : FogGerenciadorDeVendas.ConsultaReciboHomolog.NFeRetAutorizacao4Soap12, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NFeRetAutorizacao4Soap12Client : System.ServiceModel.ClientBase<FogGerenciadorDeVendas.ConsultaReciboHomolog.NFeRetAutorizacao4Soap12>, FogGerenciadorDeVendas.ConsultaReciboHomolog.NFeRetAutorizacao4Soap12 {
        
        public NFeRetAutorizacao4Soap12Client() {
        }
        
        public NFeRetAutorizacao4Soap12Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NFeRetAutorizacao4Soap12Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeRetAutorizacao4Soap12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeRetAutorizacao4Soap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FogGerenciadorDeVendas.ConsultaReciboHomolog.nfeRetAutorizacaoLoteResponse FogGerenciadorDeVendas.ConsultaReciboHomolog.NFeRetAutorizacao4Soap12.nfeRetAutorizacaoLote(FogGerenciadorDeVendas.ConsultaReciboHomolog.nfeRetAutorizacaoLoteRequest request) {
            return base.Channel.nfeRetAutorizacaoLote(request);
        }
        
        public System.Xml.XmlNode nfeRetAutorizacaoLote(System.Xml.XmlNode nfeDadosMsg) {
            FogGerenciadorDeVendas.ConsultaReciboHomolog.nfeRetAutorizacaoLoteRequest inValue = new FogGerenciadorDeVendas.ConsultaReciboHomolog.nfeRetAutorizacaoLoteRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            FogGerenciadorDeVendas.ConsultaReciboHomolog.nfeRetAutorizacaoLoteResponse retVal = ((FogGerenciadorDeVendas.ConsultaReciboHomolog.NFeRetAutorizacao4Soap12)(this)).nfeRetAutorizacaoLote(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FogGerenciadorDeVendas.ConsultaReciboHomolog.nfeRetAutorizacaoLoteResponse> FogGerenciadorDeVendas.ConsultaReciboHomolog.NFeRetAutorizacao4Soap12.nfeRetAutorizacaoLoteAsync(FogGerenciadorDeVendas.ConsultaReciboHomolog.nfeRetAutorizacaoLoteRequest request) {
            return base.Channel.nfeRetAutorizacaoLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<FogGerenciadorDeVendas.ConsultaReciboHomolog.nfeRetAutorizacaoLoteResponse> nfeRetAutorizacaoLoteAsync(System.Xml.XmlNode nfeDadosMsg) {
            FogGerenciadorDeVendas.ConsultaReciboHomolog.nfeRetAutorizacaoLoteRequest inValue = new FogGerenciadorDeVendas.ConsultaReciboHomolog.nfeRetAutorizacaoLoteRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((FogGerenciadorDeVendas.ConsultaReciboHomolog.NFeRetAutorizacao4Soap12)(this)).nfeRetAutorizacaoLoteAsync(inValue);
        }
    }
}
